name: "docker-tools"

services:
  mysql:
    image: mysql:8.0.26
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DEFAULT_DB_NAME}
    volumes:
      - ./mysql/dbdata:/var/lib/mysql
    networks:
      - docker-tools-network

  postgres:
    image: postgres:16-alpine3.20
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres/dbdata:/var/lib/postgresql/data
    networks:
      - docker-tools-network

  redis:
    image: redis:7.2.4-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - docker-tools-network

  rmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    hostname: rmq
    networks:
      - docker-tools-network

networks:
  docker-tools-network:
    name: docker-tools-network
    driver: bridge
